# Generated by Django 5.1.4 on 2024-12-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_missionandvalue_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionandvalue',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='missionandvalue',
            name='name_ru',
        ),
    ]
