# Generated by Django 5.1.4 on 2024-12-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_missionandvalue_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionandvalue',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='missionandvalue',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
