# Generated by Django 5.1.4 on 2024-12-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_description_category_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('size', models.IntegerField(default=500, help_text='Указывается объем продукта для отображения на главной странице', verbose_name='Объем')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Фото')),
                ('about_product', models.TextField(verbose_name='Об этом продукте')),
                ('description', models.TextField(verbose_name='Описание')),
                ('about_brand', models.TextField(verbose_name='О бредне')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(verbose_name='Объем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='Продукт')),
            ],
        ),
    ]
