# Generated by Django 5.1.4 on 2024-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Фотография продукта данной категории на главной странице', null=True, upload_to='categories/products/', verbose_name='Фотография продукта категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Фотография фона на странице всей продукции', null=True, upload_to='categories/banners/', verbose_name='Фото заднего фона'),
        ),
    ]
