# Generated by Django 5.1.4 on 2024-12-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='год')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'История бренда',
                'verbose_name_plural': 'История бренда',
            },
        ),
        migrations.CreateModel(
            name='BrandHistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history/images')),
                ('brand_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.brandhistory')),
            ],
        ),
    ]
