# Generated by Django 5.1.4 on 2024-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галлерея на странице "О нас"',
                'verbose_name_plural': 'Галлерея на странице "О нас"',
            },
        ),
    ]
