# Generated by Django 5.1.4 on 2024-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_photogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandhistory',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='brandhistory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='brandhistory',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
    ]
